export const TOOL_CATEGORIES = [
  "project",
  "remote-execution",
  "playwright",
  "remote-files",
  "workspace",
  "jobs",
  "context",
  "samplemanager",
] as const;

export type ToolCategory = typeof TOOL_CATEGORIES[number];

export interface ToolCatalogEntry {
  name: string;
  category: ToolCategory;
  description: string;
}

export const TOOL_CATALOG: ToolCatalogEntry[] = [
  { name: "list_projects", category: "project", description: "List projects allowed by the current MCP token." },
  { name: "project_server_links_list", category: "project", description: "List exact environment keys, server IDs, names, paths, and LIMS instance bindings for project links." },
  { name: "relay_mcp_info", category: "project", description: "Verify that the caller is connected to the Relay MCP route and version." },
  { name: "relay_core_tools", category: "project", description: "Return the stable preferred Relay MCP tools and legacy aliases." },
  { name: "relay_route_check", category: "project", description: "Check the Relay MCP route and resolve an optional project/server target without remote execution." },
  { name: "relay_unicode_check", category: "remote-execution", description: "Run a read-only SQL/PowerShell/Agent Unicode round-trip diagnostic with byte, code-point, hash, and encoding evidence." },
  { name: "relay_project_server_links_list", category: "project", description: "List project server links through the explicit Relay MCP namespace." },
  { name: "project_create", category: "project", description: "Create a project workspace and optionally link a remote server." },
  { name: "exec_remote", category: "remote-execution", description: "LEGACY compatibility tool. Prefer relay_exec_remote for all new calls." },
  { name: "exec_remote_powershell", category: "remote-execution", description: "LEGACY compatibility tool. Prefer relay_exec_remote_powershell for all new calls." },
  { name: "exec_remote_script", category: "remote-execution", description: "LEGACY compatibility tool. Prefer relay_exec_remote_script for all new calls." },
  { name: "relay_exec_remote", category: "remote-execution", description: "PREFERRED Relay MCP tool: execute a shell command on the selected linked server." },
  { name: "relay_exec_remote_powershell", category: "remote-execution", description: "PREFERRED Relay MCP tool: execute EncodedCommand PowerShell on the selected linked server." },
  { name: "relay_exec_remote_script", category: "remote-execution", description: "PREFERRED Relay MCP tool: upload and execute a PowerShell script on the selected linked server." },
  { name: "playwright_runtime_status", category: "playwright", description: "Read Agent-owned Node.js, Playwright, Chromium, and browser-cache readiness." },
  { name: "playwright_suite_list", category: "playwright", description: "List Playwright suites stored by the selected Agent." },
  { name: "playwright_suite_upload", category: "playwright", description: "Upload a Playwright test file and suite metadata with SHA-256 verification." },
  { name: "playwright_run_suite", category: "playwright", description: "Queue a formal Playwright test run through the dedicated Agent protocol." },
  { name: "playwright_run_status", category: "playwright", description: "Read a formal Playwright run record from the selected Agent." },
  { name: "playwright_artifact_list", category: "playwright", description: "List bounded Playwright artifact metadata on the selected Agent." },
  { name: "playwright_artifact_download", category: "playwright", description: "Transfer and verify a Playwright artifact through Relay into the project workspace." },
  { name: "deploy", category: "remote-execution", description: "Deploy a remote Git checkout and record commits, status, output, and rollback state." },
  { name: "fetch_logs", category: "remote-execution", description: "Fetch logs with optional time-window or deployment-run filtering." },
  { name: "restart_service", category: "remote-execution", description: "Restart Windows services, systemd units, PM2 processes, or Docker containers." },
  { name: "read_remote_file", category: "remote-files", description: "Read a text file from a linked remote server." },
  { name: "download_remote_file", category: "remote-files", description: "Stream a remote binary through Relay into the agent's local workspace." },
  { name: "write_remote_file", category: "remote-files", description: "Write UTF-8 text to a linked remote server through SFTP." },
  { name: "list_remote_files", category: "remote-files", description: "List files and directories on a linked remote server." },
  { name: "patch_remote_file", category: "remote-files", description: "Apply a unified diff to a remote text file." },
  { name: "read_local_file", category: "workspace", description: "Read UTF-8 text from the Relay project workspace." },
  { name: "workspace_info", category: "workspace", description: "Show the Relay workspace root and bounded file listing." },
  { name: "write_local_file", category: "workspace", description: "Write or append UTF-8 text in the Relay project workspace." },
  { name: "write_local_binary", category: "workspace", description: "Write a small Base64-encoded binary into the Relay workspace." },
  { name: "list_workspace_files", category: "workspace", description: "List workspace entries with optional bounded recursion." },
  { name: "workspace_file_stat", category: "workspace", description: "Inspect workspace file metadata and optionally calculate SHA-256." },
  { name: "move_workspace_file", category: "workspace", description: "Move or rename a workspace file or directory." },
  { name: "delete_workspace_file", category: "workspace", description: "Delete a workspace file or explicitly approved directory tree." },
  { name: "create_workspace_upload", category: "workspace", description: "Create a short-lived streaming upload session for a large local binary." },
  { name: "cleanup_workspace_staging", category: "workspace", description: "Preview or remove old .relay-staging entries." },
  { name: "sync_workspace", category: "workspace", description: "Synchronize the project workspace to a linked remote directory through SFTP." },
  { name: "upload_workspace_file", category: "workspace", description: "Upload one Relay workspace file to a linked remote server." },
  { name: "job_status", category: "jobs", description: "Read status, result, error, and recent logs for an async job." },
  { name: "job_list", category: "jobs", description: "List recent async jobs owned by the current user." },
  { name: "job_cancel", category: "jobs", description: "Request cancellation and close the active SSH command for a running job." },
  { name: "context_record_fact", category: "context", description: "Record a durable project fact for future MCP sessions." },
  { name: "context_search", category: "context", description: "Search durable project facts." },
  { name: "samplemanager_restart_instance", category: "samplemanager", description: "Restart core services for a SampleManager instance." },
  { name: "samplemanager_deployment_start", category: "samplemanager", description: "Start a deploymentId for correlating independent SampleManager operations." },
  { name: "samplemanager_clear_form_cache", category: "samplemanager", description: "Remove compiled FormsBin entries for one form." },
  { name: "samplemanager_recent_errors", category: "samplemanager", description: "Search recent SampleManager logs for compact error evidence." },
  { name: "samplemanager_table_schema", category: "samplemanager", description: "Inspect SQL Server columns, keys, identity, defaults, and physical mapping for a SampleManager table." },
  { name: "samplemanager_sql_query", category: "samplemanager", description: "Run parameterized SQL Server queries with escaped identifiers and detailed errors." },
  { name: "samplemanager_sql_execute_file", category: "samplemanager", description: "Run a parameterized workspace SQL file with detailed SQL Server errors." },
  { name: "samplemanager_sql_mutation", category: "samplemanager", description: "Run structured SQL mutations with dry-run rollback, backup, and before/after evidence." },
  { name: "samplemanager_apply_change_set", category: "samplemanager", description: "Apply multiple SQL changes in one transaction with idempotency keys, rollback, verification, and deployment recovery state." },
  { name: "samplemanager_run_command", category: "samplemanager", description: "Run SampleManagerCommand.exe with structured arguments." },
  { name: "samplemanager_create_entity_definition", category: "samplemanager", description: "Run CreateEntityDefinition.exe after structure source changes." },
  { name: "samplemanager_convert_tables", category: "samplemanager", description: "Run convert_table.exe separately for validated table names." },
  { name: "samplemanager_table_loader", category: "samplemanager", description: "Load a remote CSV through the built-in $table_loader VGL report." },
  { name: "samplemanager_deploy_table_loader_package", category: "samplemanager", description: "Stage, hash-verify, load, verify, and audit a table-loader package under one deploymentId." },
  { name: "samplemanager_run_utility", category: "samplemanager", description: "Run an allowlisted version-dependent SampleManager utility." },
  { name: "samplemanager_discover_build_tools", category: "samplemanager", description: "Discover MSBuild candidates in VS2022, VS2019, Framework, and PATH priority order." },
  { name: "samplemanager_build_dotnet", category: "samplemanager", description: "Build a classic SampleManager .NET solution with MSBuild." },
  { name: "samplemanager_build_deploy_assembly", category: "samplemanager", description: "Build, hash, back up, deploy, restart, and roll back one SampleManager assembly under a deploymentId." },
  { name: "samplemanager_deployment_status", category: "samplemanager", description: "Read SampleManager deployment phases, artifacts, hashes, backup, and rollback state." },
  { name: "samplemanager_deployment_finish", category: "samplemanager", description: "Finish a manually orchestrated SampleManager deploymentId as succeeded or failed." },
  { name: "samplemanager_deploy_file", category: "samplemanager", description: "Deploy a staged file into an instance area with timestamped backup." },
  { name: "samplemanager_restore_backup", category: "samplemanager", description: "Restore a specific SampleManager backup file to an explicit target." },
];

export const TOOL_CATALOG_BY_NAME = new Map(TOOL_CATALOG.map((entry) => [entry.name, entry]));
