import { useEffect, useState } from "react";
import { Activity, ArrowRight, BookOpen, CheckCircle2, ClipboardCheck, Database, FileWarning, Layers3, RefreshCw, Search, ShieldAlert, UploadCloud } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { Badge, cardClass, LifecyclePipeline, PageShell, StatePanel, StatusBadge } from "../components/KnowledgePrimitives";

type Project = { id: number; name: string };

function Metric({ label, value, hint, icon: Icon, to }: { label: string; value: unknown; hint: string; icon: typeof Activity; to: string }) {
  return <Link to={to} className={`${cardClass} block transition hover:border-indigo-700/70 hover:bg-gray-900`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wide text-gray-500">{label}</p><p className="mt-2 text-3xl font-semibold text-gray-100">{String(value ?? "—")}</p><p className="mt-1 text-xs text-gray-500">{hint}</p></div><Icon size={20} className="text-indigo-300" /></div></Link>;
}

export default function KnowledgeOverview() {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState<number>(); const [data, setData] = useState<any>(); const [capture, setCapture] = useState<any>(); const [runs, setRuns] = useState<any[]>([]); const [buildInfo, setBuildInfo] = useState<any>(); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); setError(""); Promise.all([api.listProjects(), api.knowledgeOperationsCapture(), api.knowledgeOperationsIngestRuns(8), api.knowledgeOperationsIndex(), api.health()]).then(([projectResult, captureResult, runResult, indexResult, health]) => { setProjects(projectResult.projects ?? []); const first = projectResult.projects?.[0]; setProjectId(first?.id); setCapture(captureResult); setRuns(runResult.runs ?? []); setData(indexResult); setBuildInfo(health); }).catch((err) => setError(err instanceof Error ? err.message : "Unable to load Knowledge overview")).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  if (loading && !data) return <PageShell title="Knowledge Overview" description="A map of what is authoritative, what came from project operations, and what needs review." breadcrumbs={[{ label: "Knowledge" }]}><StatePanel state="loading" message="Loading Knowledge health and pipeline summaries…" /></PageShell>;
  if (error && !data) return <PageShell title="Knowledge Overview" breadcrumbs={[{ label: "Knowledge" }]}><StatePanel state="error" message={error} onRetry={load} /></PageShell>;
  const totals = data?.index ?? {}; const captureStatus = capture?.status ?? "Unknown";
  return <PageShell title="Knowledge Overview" description="Use this page to choose the right plane. Product Knowledge is global and versioned; Project Knowledge records runtime experience; Operations explains pipeline health." breadcrumbs={[{ label: "Knowledge" }]} actions={<button onClick={load} className="inline-flex items-center gap-2 rounded-md border border-gray-700 px-3 py-2 text-xs text-gray-300 hover:bg-gray-800"><RefreshCw size={14} /> Refresh</button>}>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs text-gray-500"><ShieldAlert size={14} className="text-indigo-300" />Scope is explicit on every project page; no project selector is required for Product Knowledge.</div>{projects.length > 0 && <Badge tone="blue">{projects.length} project{projects.length === 1 ? "" : "s"} available</Badge>}</div>
    <LifecyclePipeline />
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Product documents" value={totals.documents} hint="Global authoritative sources" icon={BookOpen} to="/knowledge/product-docs" />
      <Metric label="Indexed documents" value={totals.indexedDocuments} hint={totals.stale ? "Index needs attention" : "Search coverage"} icon={Database} to="/knowledge/operations/index" />
      <Metric label="Capture state" value={captureStatus} hint={capture?.deadLetterCount ? `${capture.deadLetterCount} dead-letter records` : "No dead-letter records reported"} icon={Activity} to="/knowledge/operations/capture" />
      <Metric label="Ingest runs" value={runs.length} hint="Product and project pipeline history" icon={UploadCloud} to="/knowledge/operations/ingest" />
    </div>
    <div className="mt-6 grid gap-4 lg:grid-cols-3">
      <section className={`${cardClass} lg:col-span-2`}><div className="flex items-center justify-between"><div><h3 className="font-medium text-gray-100">Choose a Knowledge plane</h3><p className="mt-1 text-sm text-gray-500">Each plane has its own scope, permissions, and review expectations.</p></div><Layers3 size={20} className="text-indigo-300" /></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Link to="/knowledge/product-docs" className="rounded-lg border border-cyan-900/50 bg-cyan-950/20 p-4 hover:border-cyan-500/60"><p className="text-sm font-medium text-cyan-200">Product Knowledge</p><p className="mt-2 text-xs leading-5 text-gray-400">Versioned, global, authoritative documentation. Import, compare, search, and cite sources.</p><span className="mt-3 inline-flex items-center gap-1 text-xs text-cyan-300">Open plane <ArrowRight size={13} /></span></Link><Link to="/knowledge/candidates" className="rounded-lg border border-indigo-900/50 bg-indigo-950/20 p-4 hover:border-indigo-500/60"><p className="text-sm font-medium text-indigo-200">Project Knowledge</p><p className="mt-2 text-xs leading-5 text-gray-400">Evidence, candidates, cases, patterns, and playbooks with explicit lifecycle and ACL.</p><span className="mt-3 inline-flex items-center gap-1 text-xs text-indigo-300">Open plane <ArrowRight size={13} /></span></Link><Link to="/knowledge/operations/capture" className="rounded-lg border border-amber-900/50 bg-amber-950/20 p-4 hover:border-amber-500/60"><p className="text-sm font-medium text-amber-200">Operations</p><p className="mt-2 text-xs leading-5 text-gray-400">Capture health, ingestion runs, indexing, providers, and safe diagnostics.</p><span className="mt-3 inline-flex items-center gap-1 text-xs text-amber-300">Open plane <ArrowRight size={13} /></span></Link></div></section>
      <section className={cardClass}><h3 className="font-medium text-gray-100">Quick actions</h3><div className="mt-3 space-y-2"><Link to="/knowledge/product-docs/imports" className="flex items-center gap-2 rounded-md border border-gray-800 px-3 py-2 text-sm text-gray-300 hover:bg-gray-800"><UploadCloud size={15} className="text-cyan-300" /> Import Product Documents</Link><Link to="/knowledge/product-docs/search" className="flex items-center gap-2 rounded-md border border-gray-800 px-3 py-2 text-sm text-gray-300 hover:bg-gray-800"><Search size={15} className="text-cyan-300" /> Search authoritative docs</Link><Link to="/knowledge/candidates" className="flex items-center gap-2 rounded-md border border-gray-800 px-3 py-2 text-sm text-gray-300 hover:bg-gray-800"><ClipboardCheck size={15} className="text-indigo-300" /> Review candidate queue</Link><Link to="/knowledge/operations/index" className="flex items-center gap-2 rounded-md border border-gray-800 px-3 py-2 text-sm text-gray-300 hover:bg-gray-800"><RefreshCw size={15} className="text-amber-300" /> Check index/providers</Link></div></section>
    </div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><section className={cardClass}><div className="flex items-center justify-between"><h3 className="font-medium text-gray-100">Recent ingest runs</h3><Link to="/knowledge/operations/ingest" className="text-xs text-indigo-300 hover:text-indigo-200">View all</Link></div>{runs.length === 0 ? <p className="mt-4 text-sm text-gray-500">No ingest runs have been recorded yet.</p> : <div className="mt-3 divide-y divide-gray-800">{runs.slice(0, 5).map((run: any) => <Link key={run.id} to={`/knowledge/operations/ingest?run=${encodeURIComponent(run.id)}`} className="flex items-center justify-between gap-3 py-3 hover:bg-gray-800/40"><div className="min-w-0"><p className="truncate text-sm text-gray-200">{run.source_locator ?? run.id}</p><p className="mt-1 text-xs text-gray-500">{run.imported ?? 0} imported · {run.failed ?? 0} failed</p></div><StatusBadge value={run.status} /></Link>)}</div>}</section><section className={cardClass}><div className="flex items-center justify-between"><h3 className="font-medium text-gray-100">Capture diagnosis</h3><Link to="/knowledge/operations/capture" className="text-xs text-indigo-300 hover:text-indigo-200">Inspect</Link></div><div className="mt-4 flex items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-full ${/available|healthy/i.test(captureStatus) ? "bg-emerald-950 text-emerald-300" : "bg-amber-950 text-amber-300"}`}><Activity size={19} /></div><div><p className="font-medium text-gray-200">{captureStatus}</p><p className="text-xs text-gray-500">{capture?.capture?.lastError ?? capture?.diagnostics?.[0] ?? "No active diagnosis"}</p></div></div>{capture?.deadLetterCount ? <div className="mt-4 flex items-center gap-2 text-xs text-rose-300"><FileWarning size={14} /> Dead-letter records require review</div> : <div className="mt-4 flex items-center gap-2 text-xs text-emerald-300"><CheckCircle2 size={14} /> No dead-letter backlog reported</div>}</section></div>
    {projectId && <p className="mt-6 text-xs text-gray-600">Project-scoped pages default to <span className="text-gray-400">{projects.find((p) => p.id === projectId)?.name ?? `#${projectId}`}</span>; you can change it there without affecting global Product Knowledge.</p>}
    {buildInfo && <div className="mt-3 flex flex-wrap items-center gap-3 text-[11px] text-gray-600"><span>Web/MCP build {buildInfo.version}</span><span>commit {String(buildInfo.commit ?? "unknown").slice(0, 12)}</span><span>built {buildInfo.buildTime ?? "unknown"}</span></div>}
  </PageShell>;
}
