import { createHash } from "crypto";
import type { KnowledgeStore } from "./store.js";

export type RelationType = "menu_task" | "task_assembly" | "form_control" | "control_property" | "form_cache" | "form_registration" | "entity_property" | "assembly_reference" | "deployment_component" | "cache_reference" | "task_entity" | "depends_on" | "supersedes" | string;
export interface RelationScope { sampleManagerVersion?: string; solution?: string; module?: string; environment?: string; sourceSha256?: string; }
export interface ExtractedRelation extends RelationScope { from: string; to: string; relationType: RelationType; sourceLocator: string; confidence: number; verified: boolean; extractionVersion: string; }
export type SampleManagerSourceKind = "form-xml" | "form-registration" | "form_registration" | "task-source" | "csharp" | "csharp-project" | "assembly" | "menu" | "master-menu" | "entity-definition" | "entity" | "formsbin" | "forms-bin" | "manifest" | "deployment-manifest" | "deployment_manifest";
export interface RelationExtractionInput extends RelationScope { content: string; sourceLocator: string; kind: SampleManagerSourceKind | (string & {}); verified?: boolean; confidence?: number; extractionVersion?: string; }

const EXTRACTION_VERSION = "relations-v2";
function hash(value: string): string { return createHash("sha256").update(value, "utf8").digest("hex"); }
function scopeSuffix(scope: RelationScope): string { return [scope.sampleManagerVersion && `sm=${scope.sampleManagerVersion}`, scope.solution && `solution=${scope.solution}`, scope.module && `module=${scope.module}`, scope.environment && `env=${scope.environment}`].filter(Boolean).join("|"); }
function objectId(prefix: string, value: string, scope: RelationScope = {}): string { const scoped = scopeSuffix(scope); return `${prefix}-${hash(`${value}${scoped ? `|${scoped}` : ""}`).slice(0, 24)}`; }
function xmlAttributes(tag: string): Record<string, string> { const out: Record<string, string> = {}; for (const match of tag.matchAll(/([A-Za-z_][\w:.-]*)\s*=\s*["']([^"']*)["']/g)) out[match[1].toLowerCase()] = match[2]; return out; }
function clean(value: string | undefined): string | undefined { const result = value?.trim(); return result ? result : undefined; }

/** Extract only relationships explicitly present in deterministic source text. */
export function extractSampleManagerRelations(input: RelationExtractionInput): ExtractedRelation[] {
  const scope: RelationScope = { sampleManagerVersion: input.sampleManagerVersion, solution: input.solution, module: input.module, environment: input.environment, sourceSha256: input.sourceSha256 ?? hash(input.content) };
  const version = input.extractionVersion ?? EXTRACTION_VERSION, baseConfidence = input.confidence ?? 1, verified = input.verified ?? true, edges: ExtractedRelation[] = [];
  const add = (fromPrefix: string, from: string, toPrefix: string, to: string, relationType: RelationType, confidence = baseConfidence, isVerified = verified) => { const f = clean(from), t = clean(to); if (!f || !t) return; edges.push({ from: objectId(fromPrefix, f, scope), to: objectId(toPrefix, t, scope), relationType, sourceLocator: input.sourceLocator, confidence: Math.max(0, Math.min(1, confidence)), verified: isVerified, extractionVersion: version, ...scope }); };
  const content = input.content;
  if (input.kind === "form-xml") {
    const formTag = content.match(/<Form\b[^>]*>/i), formAttrs = formTag ? xmlAttributes(formTag[0]) : {}, form = formAttrs.name ?? formAttrs.id ?? clean(input.sourceLocator);
    for (const match of content.matchAll(/<(?:Control|Field)\b[^>]*>/gi)) { const attrs = xmlAttributes(match[0]), control = attrs.name ?? attrs.id; if (!control) continue; add("form", form!, "control", `${form}:${control}`, "form_control"); const property = attrs.property ?? attrs.binding ?? attrs.field; if (property) add("control", `${form}:${control}`, "property", `${control}:${property}`, "control_property"); }
    for (const match of content.matchAll(/<Property\b[^>]*>/gi)) { const attrs = xmlAttributes(match[0]); add("control", `${form}:${attrs.control ?? attrs.owner ?? ""}`, "property", attrs.name ?? attrs.id ?? attrs.value ?? "", "control_property"); }
    for (const match of content.matchAll(/(?:cache|FormsBin)(?:Name)?\s*[=:]\s*["']?([^\s"'<>,;]+)/gi)) add("form", form!, "cache", match[1], "form_cache");
  } else if (input.kind === "form-registration" || input.kind === "form_registration") {
    for (const m of content.matchAll(/(?:FormRegistration|RegisterForm|FORM_REGISTRATION)\b[^\n\r>]*/gi)) { const a = xmlAttributes(m[0]); add("form", a.form ?? a.name ?? a.id ?? "", "task", a.class ?? a.type ?? a.handler ?? a.task ?? "", "form_registration"); }
    for (const m of content.matchAll(/(?:form|Form)\s*[|,:=]\s*([\w.:-]+)\s*[|,:=]\s*([\w.:-]+)/g)) add("form", m[1], "task", m[2], "form_registration", 0.95);
  } else if (input.kind === "task-source" || input.kind === "csharp" || input.kind === "csharp-project" || input.kind === "assembly") {
    const taskNames = new Set<string>(); for (const m of content.matchAll(/(?:TaskName|SampleManagerTask|class)\s*[:=(\s"']+([A-Za-z_][\w.]*)/gi)) taskNames.add(m[1]); for (const m of content.matchAll(/\[\s*SampleManagerTask\s*\(\s*["']([^"']+)["']/gi)) taskNames.add(m[1]);
    const assemblies = [...new Set([...content.matchAll(/(?:Assembly(?:Name|Path)?|assembly|typeof\s+|Reference\s*=)\s*[:=]?\s*["']?([A-Za-z_][\w.\\/-]*(?:\.dll|Assembly))\b/gi)].map((m) => m[1]))];
    for (const task of taskNames) for (const assembly of assemblies) add("task", task, "assembly", assembly, "task_assembly", 0.95);
    for (const m of content.matchAll(/(?:AssemblyTitle|AssemblyName|<AssemblyName>)\s*[=:>\s]+["']?([A-Za-z_][\w.-]*)/gi)) for (const task of taskNames) add("task", task, "assembly", m[1], "task_assembly", 0.9);
    for (const m of content.matchAll(/(?:Reference|DependsOn|AssemblyRef)\s*[=:]\s*["']?([A-Za-z_][\w.\\/-]*\.dll)/gi)) add("assembly", clean(input.sourceLocator)!, "assembly", m[1], "assembly_reference", 0.9);
  } else if (input.kind === "menu" || input.kind === "master-menu") {
    for (const m of content.matchAll(/<Menu(?:Item)?\b[^>]*>/gi)) { const a = xmlAttributes(m[0]); add("menu", a.name ?? a.id ?? a.caption ?? "", "task", a.task ?? a.command ?? a.action ?? "", "menu_task", 0.95); }
    for (const line of content.split(/\r?\n/)) { const p = line.split(/[|,;\t]/).map((v) => v.trim()).filter(Boolean); if (p.length >= 2) add("menu", p[0], "task", p[1], "menu_task", 0.9); }
  } else if (input.kind === "entity-definition" || input.kind === "entity") {
    let entity = ""; for (const m of content.matchAll(/<Entity\b[^>]*>/gi)) { const a = xmlAttributes(m[0]); entity = a.name ?? a.id ?? ""; } entity = entity || clean(content.match(/(?:Entity|ENTITY)\s*[=:]\s*["']?([\w.-]+)/)?.[1]) || clean(input.sourceLocator) || "entity";
    for (const m of content.matchAll(/<(?:Property|Field)\b[^>]*>/gi)) { const a = xmlAttributes(m[0]); add("entity", entity, "property", a.name ?? a.id ?? "", "entity_property"); }
    for (const m of content.matchAll(/(?:Property|Field)\s*[=:]\s*["']?([\w.-]+)/gi)) add("entity", entity, "property", m[1], "entity_property", 0.95);
  } else if (input.kind === "formsbin" || input.kind === "forms-bin") {
    for (const m of content.matchAll(/(?:Form|form)\s*[=:]\s*([^,;\s]+)[,;\s]+(?:Cache|cache|FormsBin)\s*[=:]\s*([^,;\s]+)/g)) add("form", m[1], "cache", m[2], "form_cache"); for (const m of content.matchAll(/([\w.:-]+)\s*[-=]>\s*([\w./\\:-]+)/g)) add("form", m[1], "cache", m[2], "form_cache", 0.9);
  } else {
    let parsed: unknown; try { parsed = JSON.parse(content); } catch { parsed = undefined; } const manifest = clean(input.sourceLocator) || "deployment-manifest";
    const visit = (value: unknown, key = "") => { if (typeof value === "string" && /(?:form|task|assembly|cache|component|module)/i.test(key)) add("manifest", manifest, key.toLowerCase().includes("assembly") ? "assembly" : key.toLowerCase().includes("task") ? "task" : key.toLowerCase().includes("form") ? "form" : key.toLowerCase().includes("cache") ? "cache" : "component", value, "deployment_component", 0.9); else if (Array.isArray(value)) value.forEach((item) => visit(item, key)); else if (value && typeof value === "object") Object.entries(value).forEach(([k, v]) => visit(v, k)); };
    if (parsed !== undefined) visit(parsed); else for (const m of content.matchAll(/(?:form|task|assembly|cache|component)\s*[=:]\s*["']?([^\s"',;}]+)/gi)) add("manifest", manifest, m[0].split(/[=:]/)[0].trim(), m[1], "deployment_component", 0.85, false);
  }
  return edges;
}

function ensureObjectDocument(store: KnowledgeStore, id: string, sourceLocator: string, projectId: string | undefined, scope: RelationScope): void { if (store.db.prepare("SELECT id FROM knowledge_documents WHERE id = ?").get(id)) return; const now = new Date().toISOString(); store.upsertDocument({ id, kind: "case", title: id, body: `Deterministic SampleManager object ${id}`, lifecycle: "draft", projectId, sampleManagerVersion: scope.sampleManagerVersion, solution: scope.solution, module: scope.module, environment: scope.environment, locator: sourceLocator, sha256: scope.sourceSha256 ?? hash(id), createdAt: now, updatedAt: now }); }
export function persistRelations(store: KnowledgeStore, relations: ExtractedRelation[], projectId?: string): number { let inserted = 0; for (const relation of relations) { const scope: RelationScope = relation, from = projectId ? `${projectId}:${relation.from}` : relation.from, to = projectId ? `${projectId}:${relation.to}` : relation.to; ensureObjectDocument(store, from, relation.sourceLocator, projectId, scope); ensureObjectDocument(store, to, relation.sourceLocator, projectId, scope); const result = store.db.prepare(`INSERT OR IGNORE INTO knowledge_relations(id,from_document_id,to_document_id,relation_type,source_locator,confidence,verified,extraction_version,created_at,project_id,samplemanager_version,solution,module,environment,source_sha256) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(`${objectId("relation", `${projectId ?? ""}:${from}:${to}:${relation.relationType}:${relation.sourceLocator}`, scope)}`, from, to, relation.relationType, relation.sourceLocator, relation.confidence, relation.verified ? 1 : 0, relation.extractionVersion, new Date().toISOString(), projectId ?? null, scope.sampleManagerVersion ?? null, scope.solution ?? null, scope.module ?? null, scope.environment ?? null, scope.sourceSha256 ?? null); if (result.changes === 1) inserted++; if (projectId) store.audit({ projectId, action: "knowledge.relation.created", entityType: "relation", entityId: `${relation.from}:${relation.to}`, details: { relationType: relation.relationType, sourceLocator: relation.sourceLocator, confidence: relation.confidence, verified: relation.verified, extractionVersion: relation.extractionVersion } }); } return inserted; }

export interface RelationQueryRequest { userId: number; projectId: string; objectId?: string; relationType?: RelationType; verifiedOnly?: boolean; limit?: number; sampleManagerVersion?: string; solution?: string; module?: string; environment?: string; }
export function queryRelations(store: KnowledgeStore, request: RelationQueryRequest) { if (!store.canRead(request.userId, request.projectId)) throw new Error("Knowledge access denied for project"); const conditions = ["r.project_id = @projectId"], params: Record<string, unknown> = { projectId: request.projectId }; if (request.objectId) { const scopedObjectId = request.objectId.startsWith(`${request.projectId}:`) ? request.objectId : `${request.projectId}:${request.objectId}`; conditions.push("(r.from_document_id = @objectId OR r.to_document_id = @objectId)"); params.objectId = scopedObjectId; } if (request.relationType) { conditions.push("r.relation_type = @relationType"); params.relationType = request.relationType; } if (request.verifiedOnly) conditions.push("r.verified = 1"); for (const [column, value] of [["samplemanager_version", request.sampleManagerVersion], ["solution", request.solution], ["module", request.module], ["environment", request.environment]] as const) if (value) { conditions.push(`(r.${column} IS NULL OR r.${column} = @${column})`); params[column] = value; } const limit = Math.max(1, Math.min(request.limit ?? 100, 500)); const rows = store.db.prepare(`SELECT r.*, f.title AS from_title, t.title AS to_title FROM knowledge_relations r JOIN knowledge_documents f ON f.id = r.from_document_id JOIN knowledge_documents t ON t.id = r.to_document_id WHERE ${conditions.join(" AND ")} ORDER BY r.created_at DESC LIMIT ${limit}`).all(params) as Array<Record<string, unknown>>; return rows.map((row) => ({ id: String(row.id), from: { id: String(row.from_document_id), title: String(row.from_title) }, to: { id: String(row.to_document_id), title: String(row.to_title) }, relationType: String(row.relation_type), sourceLocator: String(row.source_locator), sourceSha256: row.source_sha256 ? String(row.source_sha256) : undefined, confidence: Number(row.confidence), verified: Number(row.verified) === 1, extractionVersion: String(row.extraction_version), sampleManagerVersion: row.samplemanager_version ? String(row.samplemanager_version) : undefined, solution: row.solution ? String(row.solution) : undefined, module: row.module ? String(row.module) : undefined, environment: row.environment ? String(row.environment) : undefined, createdAt: String(row.created_at) })); }

export function analyzeRelationImpact(store: KnowledgeStore, request: RelationQueryRequest & { maxDepth?: number; direction?: "upstream" | "downstream" | "both" }) { const depthLimit = Math.max(0, Math.min(request.maxDepth ?? 3, 20)), direction = request.direction ?? "both", root = request.objectId ?? ""; if (!root) return { root, depth: depthLimit, nodes: [], relations: [] }; const seen = new Set<string>([root.startsWith(`${request.projectId}:`) ? root : `${request.projectId}:${root}`]); let frontier = [...seen]; const all: ReturnType<typeof queryRelations> = []; for (let depth = 0; depth <= depthLimit && frontier.length; depth++) { const next: string[] = []; for (const node of frontier) for (const relation of queryRelations(store, { ...request, objectId: node })) { const outward = direction === "downstream" ? relation.from.id === node : direction === "upstream" ? relation.to.id === node : true; if (!outward) continue; if (!all.some((item) => item.id === relation.id)) all.push(relation); const candidate = relation.from.id === node ? relation.to.id : relation.from.id; if (!seen.has(candidate)) { seen.add(candidate); next.push(candidate); } } frontier = next; } return { root, depth: depthLimit, nodes: [...seen], relations: all }; }
